/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GanttRouteImport } from './routes/gantt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentIndexRouteImport } from './routes/talent.index'
import { Route as ShootDaysIndexRouteImport } from './routes/shoot-days.index'
import { Route as HandoffIndexRouteImport } from './routes/handoff.index'
import { Route as TalentWorkflowRouteImport } from './routes/talent.workflow'
import { Route as TalentTimelineRouteImport } from './routes/talent.timeline'
import { Route as TalentAuditRouteImport } from './routes/talent.audit'
import { Route as TalentTalentIdRouteImport } from './routes/talent.$talentId'
import { Route as ShootDaysDayIdRouteImport } from './routes/shoot-days.$dayId'
import { Route as HandoffSlugRouteImport } from './routes/handoff.$slug'
import { Route as EpisodesSlugRouteImport } from './routes/episodes.$slug'

const GanttRoute = GanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootDaysIndexRoute = ShootDaysIndexRouteImport.update({
  id: '/shoot-days/',
  path: '/shoot-days/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffIndexRoute = HandoffIndexRouteImport.update({
  id: '/handoff/',
  path: '/handoff/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentWorkflowRoute = TalentWorkflowRouteImport.update({
  id: '/talent/workflow',
  path: '/talent/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentTimelineRoute = TalentTimelineRouteImport.update({
  id: '/talent/timeline',
  path: '/talent/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentAuditRoute = TalentAuditRouteImport.update({
  id: '/talent/audit',
  path: '/talent/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentTalentIdRoute = TalentTalentIdRouteImport.update({
  id: '/talent/$talentId',
  path: '/talent/$talentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootDaysDayIdRoute = ShootDaysDayIdRouteImport.update({
  id: '/shoot-days/$dayId',
  path: '/shoot-days/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffSlugRoute = HandoffSlugRouteImport.update({
  id: '/handoff/$slug',
  path: '/handoff/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesSlugRoute = EpisodesSlugRouteImport.update({
  id: '/episodes/$slug',
  path: '/episodes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gantt': typeof GanttRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/handoff/$slug': typeof HandoffSlugRoute
  '/shoot-days/$dayId': typeof ShootDaysDayIdRoute
  '/talent/$talentId': typeof TalentTalentIdRoute
  '/talent/audit': typeof TalentAuditRoute
  '/talent/timeline': typeof TalentTimelineRoute
  '/talent/workflow': typeof TalentWorkflowRoute
  '/handoff/': typeof HandoffIndexRoute
  '/shoot-days/': typeof ShootDaysIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gantt': typeof GanttRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/handoff/$slug': typeof HandoffSlugRoute
  '/shoot-days/$dayId': typeof ShootDaysDayIdRoute
  '/talent/$talentId': typeof TalentTalentIdRoute
  '/talent/audit': typeof TalentAuditRoute
  '/talent/timeline': typeof TalentTimelineRoute
  '/talent/workflow': typeof TalentWorkflowRoute
  '/handoff': typeof HandoffIndexRoute
  '/shoot-days': typeof ShootDaysIndexRoute
  '/talent': typeof TalentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gantt': typeof GanttRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/handoff/$slug': typeof HandoffSlugRoute
  '/shoot-days/$dayId': typeof ShootDaysDayIdRoute
  '/talent/$talentId': typeof TalentTalentIdRoute
  '/talent/audit': typeof TalentAuditRoute
  '/talent/timeline': typeof TalentTimelineRoute
  '/talent/workflow': typeof TalentWorkflowRoute
  '/handoff/': typeof HandoffIndexRoute
  '/shoot-days/': typeof ShootDaysIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gantt'
    | '/episodes/$slug'
    | '/handoff/$slug'
    | '/shoot-days/$dayId'
    | '/talent/$talentId'
    | '/talent/audit'
    | '/talent/timeline'
    | '/talent/workflow'
    | '/handoff/'
    | '/shoot-days/'
    | '/talent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gantt'
    | '/episodes/$slug'
    | '/handoff/$slug'
    | '/shoot-days/$dayId'
    | '/talent/$talentId'
    | '/talent/audit'
    | '/talent/timeline'
    | '/talent/workflow'
    | '/handoff'
    | '/shoot-days'
    | '/talent'
  id:
    | '__root__'
    | '/'
    | '/gantt'
    | '/episodes/$slug'
    | '/handoff/$slug'
    | '/shoot-days/$dayId'
    | '/talent/$talentId'
    | '/talent/audit'
    | '/talent/timeline'
    | '/talent/workflow'
    | '/handoff/'
    | '/shoot-days/'
    | '/talent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GanttRoute: typeof GanttRoute
  EpisodesSlugRoute: typeof EpisodesSlugRoute
  HandoffSlugRoute: typeof HandoffSlugRoute
  ShootDaysDayIdRoute: typeof ShootDaysDayIdRoute
  TalentTalentIdRoute: typeof TalentTalentIdRoute
  TalentAuditRoute: typeof TalentAuditRoute
  TalentTimelineRoute: typeof TalentTimelineRoute
  TalentWorkflowRoute: typeof TalentWorkflowRoute
  HandoffIndexRoute: typeof HandoffIndexRoute
  ShootDaysIndexRoute: typeof ShootDaysIndexRoute
  TalentIndexRoute: typeof TalentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gantt': {
      id: '/gantt'
      path: '/gantt'
      fullPath: '/gantt'
      preLoaderRoute: typeof GanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-days/': {
      id: '/shoot-days/'
      path: '/shoot-days'
      fullPath: '/shoot-days/'
      preLoaderRoute: typeof ShootDaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/': {
      id: '/handoff/'
      path: '/handoff'
      fullPath: '/handoff/'
      preLoaderRoute: typeof HandoffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/workflow': {
      id: '/talent/workflow'
      path: '/talent/workflow'
      fullPath: '/talent/workflow'
      preLoaderRoute: typeof TalentWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/timeline': {
      id: '/talent/timeline'
      path: '/talent/timeline'
      fullPath: '/talent/timeline'
      preLoaderRoute: typeof TalentTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/audit': {
      id: '/talent/audit'
      path: '/talent/audit'
      fullPath: '/talent/audit'
      preLoaderRoute: typeof TalentAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/$talentId': {
      id: '/talent/$talentId'
      path: '/talent/$talentId'
      fullPath: '/talent/$talentId'
      preLoaderRoute: typeof TalentTalentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-days/$dayId': {
      id: '/shoot-days/$dayId'
      path: '/shoot-days/$dayId'
      fullPath: '/shoot-days/$dayId'
      preLoaderRoute: typeof ShootDaysDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$slug': {
      id: '/handoff/$slug'
      path: '/handoff/$slug'
      fullPath: '/handoff/$slug'
      preLoaderRoute: typeof HandoffSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$slug': {
      id: '/episodes/$slug'
      path: '/episodes/$slug'
      fullPath: '/episodes/$slug'
      preLoaderRoute: typeof EpisodesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GanttRoute: GanttRoute,
  EpisodesSlugRoute: EpisodesSlugRoute,
  HandoffSlugRoute: HandoffSlugRoute,
  ShootDaysDayIdRoute: ShootDaysDayIdRoute,
  TalentTalentIdRoute: TalentTalentIdRoute,
  TalentAuditRoute: TalentAuditRoute,
  TalentTimelineRoute: TalentTimelineRoute,
  TalentWorkflowRoute: TalentWorkflowRoute,
  HandoffIndexRoute: HandoffIndexRoute,
  ShootDaysIndexRoute: ShootDaysIndexRoute,
  TalentIndexRoute: TalentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
