/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentIndexRouteImport } from './routes/talent.index'
import { Route as ShootDaysIndexRouteImport } from './routes/shoot-days.index'
import { Route as ShootDaysDayIdRouteImport } from './routes/shoot-days.$dayId'
import { Route as EpisodesSlugRouteImport } from './routes/episodes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootDaysIndexRoute = ShootDaysIndexRouteImport.update({
  id: '/shoot-days/',
  path: '/shoot-days/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootDaysDayIdRoute = ShootDaysDayIdRouteImport.update({
  id: '/shoot-days/$dayId',
  path: '/shoot-days/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesSlugRoute = EpisodesSlugRouteImport.update({
  id: '/episodes/$slug',
  path: '/episodes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/shoot-days/$dayId': typeof ShootDaysDayIdRoute
  '/shoot-days/': typeof ShootDaysIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/shoot-days/$dayId': typeof ShootDaysDayIdRoute
  '/shoot-days': typeof ShootDaysIndexRoute
  '/talent': typeof TalentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/shoot-days/$dayId': typeof ShootDaysDayIdRoute
  '/shoot-days/': typeof ShootDaysIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/episodes/$slug'
    | '/shoot-days/$dayId'
    | '/shoot-days/'
    | '/talent/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/episodes/$slug' | '/shoot-days/$dayId' | '/shoot-days' | '/talent'
  id:
    | '__root__'
    | '/'
    | '/episodes/$slug'
    | '/shoot-days/$dayId'
    | '/shoot-days/'
    | '/talent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpisodesSlugRoute: typeof EpisodesSlugRoute
  ShootDaysDayIdRoute: typeof ShootDaysDayIdRoute
  ShootDaysIndexRoute: typeof ShootDaysIndexRoute
  TalentIndexRoute: typeof TalentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-days/': {
      id: '/shoot-days/'
      path: '/shoot-days'
      fullPath: '/shoot-days/'
      preLoaderRoute: typeof ShootDaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-days/$dayId': {
      id: '/shoot-days/$dayId'
      path: '/shoot-days/$dayId'
      fullPath: '/shoot-days/$dayId'
      preLoaderRoute: typeof ShootDaysDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$slug': {
      id: '/episodes/$slug'
      path: '/episodes/$slug'
      fullPath: '/episodes/$slug'
      preLoaderRoute: typeof EpisodesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpisodesSlugRoute: EpisodesSlugRoute,
  ShootDaysDayIdRoute: ShootDaysDayIdRoute,
  ShootDaysIndexRoute: ShootDaysIndexRoute,
  TalentIndexRoute: TalentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
