/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as GanttRouteImport } from './routes/gantt'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentIndexRouteImport } from './routes/talent.index'
import { Route as ShootDaysIndexRouteImport } from './routes/shoot-days.index'
import { Route as HandoffIndexRouteImport } from './routes/handoff.index'
import { Route as TalentWorkflowRouteImport } from './routes/talent.workflow'
import { Route as TalentTimelineRouteImport } from './routes/talent.timeline'
import { Route as TalentAuditRouteImport } from './routes/talent.audit'
import { Route as TalentTalentIdRouteImport } from './routes/talent.$talentId'
import { Route as ShootDaysDayIdRouteImport } from './routes/shoot-days.$dayId'
import { Route as HandoffSlugRouteImport } from './routes/handoff.$slug'
import { Route as EpisodesSlugRouteImport } from './routes/episodes.$slug'

const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const GanttRoute = GanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootDaysIndexRoute = ShootDaysIndexRouteImport.update({
  id: '/shoot-days/',
  path: '/shoot-days/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffIndexRoute = HandoffIndexRouteImport.update({
  id: '/handoff/',
  path: '/handoff/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentWorkflowRoute = TalentWorkflowRouteImport.update({
  id: '/talent/workflow',
  path: '/talent/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentTimelineRoute = TalentTimelineRouteImport.update({
  id: '/talent/timeline',
  path: '/talent/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentAuditRoute = TalentAuditRouteImport.update({
  id: '/talent/audit',
  path: '/talent/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentTalentIdRoute = TalentTalentIdRouteImport.update({
  id: '/talent/$talentId',
  path: '/talent/$talentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootDaysDayIdRoute = ShootDaysDayIdRouteImport.update({
  id: '/shoot-days/$dayId',
  path: '/shoot-days/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffSlugRoute = HandoffSlugRouteImport.update({
  id: '/handoff/$slug',
  path: '/handoff/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesSlugRoute = EpisodesSlugRouteImport.update({
  id: '/episodes/$slug',
  path: '/episodes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/gantt': typeof GanttRoute
  '/publish': typeof PublishRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/handoff/$slug': typeof HandoffSlugRoute
  '/shoot-days/$dayId': typeof ShootDaysDayIdRoute
  '/talent/$talentId': typeof TalentTalentIdRoute
  '/talent/audit': typeof TalentAuditRoute
  '/talent/timeline': typeof TalentTimelineRoute
  '/talent/workflow': typeof TalentWorkflowRoute
  '/handoff/': typeof HandoffIndexRoute
  '/shoot-days/': typeof ShootDaysIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/gantt': typeof GanttRoute
  '/publish': typeof PublishRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/handoff/$slug': typeof HandoffSlugRoute
  '/shoot-days/$dayId': typeof ShootDaysDayIdRoute
  '/talent/$talentId': typeof TalentTalentIdRoute
  '/talent/audit': typeof TalentAuditRoute
  '/talent/timeline': typeof TalentTimelineRoute
  '/talent/workflow': typeof TalentWorkflowRoute
  '/handoff': typeof HandoffIndexRoute
  '/shoot-days': typeof ShootDaysIndexRoute
  '/talent': typeof TalentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/gantt': typeof GanttRoute
  '/publish': typeof PublishRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/handoff/$slug': typeof HandoffSlugRoute
  '/shoot-days/$dayId': typeof ShootDaysDayIdRoute
  '/talent/$talentId': typeof TalentTalentIdRoute
  '/talent/audit': typeof TalentAuditRoute
  '/talent/timeline': typeof TalentTimelineRoute
  '/talent/workflow': typeof TalentWorkflowRoute
  '/handoff/': typeof HandoffIndexRoute
  '/shoot-days/': typeof ShootDaysIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/crew'
    | '/dashboard'
    | '/gantt'
    | '/publish'
    | '/episodes/$slug'
    | '/handoff/$slug'
    | '/shoot-days/$dayId'
    | '/talent/$talentId'
    | '/talent/audit'
    | '/talent/timeline'
    | '/talent/workflow'
    | '/handoff/'
    | '/shoot-days/'
    | '/talent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/crew'
    | '/dashboard'
    | '/gantt'
    | '/publish'
    | '/episodes/$slug'
    | '/handoff/$slug'
    | '/shoot-days/$dayId'
    | '/talent/$talentId'
    | '/talent/audit'
    | '/talent/timeline'
    | '/talent/workflow'
    | '/handoff'
    | '/shoot-days'
    | '/talent'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/crew'
    | '/dashboard'
    | '/gantt'
    | '/publish'
    | '/episodes/$slug'
    | '/handoff/$slug'
    | '/shoot-days/$dayId'
    | '/talent/$talentId'
    | '/talent/audit'
    | '/talent/timeline'
    | '/talent/workflow'
    | '/handoff/'
    | '/shoot-days/'
    | '/talent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  CrewRoute: typeof CrewRoute
  DashboardRoute: typeof DashboardRoute
  GanttRoute: typeof GanttRoute
  PublishRoute: typeof PublishRoute
  EpisodesSlugRoute: typeof EpisodesSlugRoute
  HandoffSlugRoute: typeof HandoffSlugRoute
  ShootDaysDayIdRoute: typeof ShootDaysDayIdRoute
  TalentTalentIdRoute: typeof TalentTalentIdRoute
  TalentAuditRoute: typeof TalentAuditRoute
  TalentTimelineRoute: typeof TalentTimelineRoute
  TalentWorkflowRoute: typeof TalentWorkflowRoute
  HandoffIndexRoute: typeof HandoffIndexRoute
  ShootDaysIndexRoute: typeof ShootDaysIndexRoute
  TalentIndexRoute: typeof TalentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gantt': {
      id: '/gantt'
      path: '/gantt'
      fullPath: '/gantt'
      preLoaderRoute: typeof GanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-days/': {
      id: '/shoot-days/'
      path: '/shoot-days'
      fullPath: '/shoot-days/'
      preLoaderRoute: typeof ShootDaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/': {
      id: '/handoff/'
      path: '/handoff'
      fullPath: '/handoff/'
      preLoaderRoute: typeof HandoffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/workflow': {
      id: '/talent/workflow'
      path: '/talent/workflow'
      fullPath: '/talent/workflow'
      preLoaderRoute: typeof TalentWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/timeline': {
      id: '/talent/timeline'
      path: '/talent/timeline'
      fullPath: '/talent/timeline'
      preLoaderRoute: typeof TalentTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/audit': {
      id: '/talent/audit'
      path: '/talent/audit'
      fullPath: '/talent/audit'
      preLoaderRoute: typeof TalentAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/$talentId': {
      id: '/talent/$talentId'
      path: '/talent/$talentId'
      fullPath: '/talent/$talentId'
      preLoaderRoute: typeof TalentTalentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-days/$dayId': {
      id: '/shoot-days/$dayId'
      path: '/shoot-days/$dayId'
      fullPath: '/shoot-days/$dayId'
      preLoaderRoute: typeof ShootDaysDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$slug': {
      id: '/handoff/$slug'
      path: '/handoff/$slug'
      fullPath: '/handoff/$slug'
      preLoaderRoute: typeof HandoffSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$slug': {
      id: '/episodes/$slug'
      path: '/episodes/$slug'
      fullPath: '/episodes/$slug'
      preLoaderRoute: typeof EpisodesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  CrewRoute: CrewRoute,
  DashboardRoute: DashboardRoute,
  GanttRoute: GanttRoute,
  PublishRoute: PublishRoute,
  EpisodesSlugRoute: EpisodesSlugRoute,
  HandoffSlugRoute: HandoffSlugRoute,
  ShootDaysDayIdRoute: ShootDaysDayIdRoute,
  TalentTalentIdRoute: TalentTalentIdRoute,
  TalentAuditRoute: TalentAuditRoute,
  TalentTimelineRoute: TalentTimelineRoute,
  TalentWorkflowRoute: TalentWorkflowRoute,
  HandoffIndexRoute: HandoffIndexRoute,
  ShootDaysIndexRoute: ShootDaysIndexRoute,
  TalentIndexRoute: TalentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
